 @startuml
 skinparam style strictuml
 skinparam DefaultFontName Arial
 skinparam DefaultFontSize 16
 skinparam DefaultFontStyle bold
 skinparam ArrowThickness 2.2
 skinparam ArrowColor #gray
 hide empty members

 title Réserver un livre de la bibliothèque  \n<I>Exercice MDD (classes, attributs, associations)</i>\nLOG210-01 C. Fuhrman\n Vincent Audette

 class "Membre" as mb {
   nom : String
 }

 class "Bibliothèque" as bib {

 }

 class "Reservation" as rsv {
     noConfirmation: int
     dateTimeReservation: DateTime
     dateTimeRetour: DateTime
 }

 class "CatalogueLivre" as cat

 class "Exemplaire" as exemp {
     codeIdentification: String
     estDisponible: boolean
 }

 class "Livre" as livre {
      ISBN: String
      auteur: String
      titre: String
      maisonEdition: String
      numéroEdition: int
      année: int
 }


 bib "1" -- "1" cat : Offre >
 bib "1" -- "*" mb: Sert >
 bib "1" -- "*" rsv: Gère >
 cat "1" *-- "*" livre: Contiens >
 livre "1" -- "1..*" exemp: Décrit >
 mb "1" -- "*" rsv: Effectue >
 rsv "0..1" -- "1" exemp: Réserve >


 @enduml